### ISSUE TITLE
Carta registrada não disponível?

### ISSUE THREAD

**Issue by mmascia** [pedro-teixeira/correios#246]
Olá,
Acredito que isso afete poucas pessoas, mas em minha loja utilizo o frete por carta registrada e após atualizar para a 4.8.0 esta opção não aparece mais. Realmente foi removida?

Obrigado!

**Comment by rafaelpatro** [comment]
Também uso Carta. Se tiver acesso ao SIGEPWeb, é só atualizar os serviços no painel de configurações do módulo. Senão pode adicionar diretamente no banco na tabela _correios_postmethods_.

**Comment by brumevi** [comment]
Olá, 
@rafaelpatro  também utilizo carta, já tentei várias vezes colocar a senha do sigepweb mas opção de carta não aparece, poderia me ajudar?
obs: o sistema de carta estando ativo só será listado para produtos com peso até 500g que é o limite do serviço?

**Comment by rafaelpatro** [comment]
Sim. O módulo respeita o limite de peso.
Salva as configurações, após preencher usuário e senha. E só então clique
em Atualizar serviços.
Avise se aparecer algum erro.

Em 28/06/2017 23:24, "brumevi" <notifications@github.com> escreveu:

Olá,
@rafaelpatro <https://github.com/rafaelpatro> também utilizo carta, já
tentei várias vezes colocar a senha do sigepweb mas opção de carta não
aparece, poderia me ajudar?
obs: o sistema de carta estando ativo só será listado para produtos com
peso até 500g que é o limite do serviço?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pedro-teixeira/correios/issues/246#issuecomment-311844231>,
or mute the thread

**Comment by rafaelpatro** [comment]
*Salve as conf...

**Comment by brumevi** [comment]
muito obrigado, deu certo, 
consigo mudar o nome do do serviço CARTA COMERCIAL para quando aparecer para o cliente? muita gente não conhece e acredito possa ficar com receio de escolher

**Comment by rafaelpatro** [comment]
Sim. Atualiza a cache de Traduções e testa no frontend. Por enquanto o
arquivo de traduções está configurado apenas para o frontend.

Em 29/06/2017 08:37, "brumevi" <notifications@github.com> escreveu:

**Comment by brumevi** [comment]
para quem não é desenvolvedor consegue realizar essa tarefa? você presta serviços para magento?

**Comment by rafaelpatro** [comment]
É simples, você consegue. To no celular agora, mais tarde te passo
orientação.

Em 29/06/2017 09:31, "brumevi" <notifications@github.com> escreveu:

para quem não é desenvolvedor consegue realizar essa tarefa? você presta
serviços para magento?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pedro-teixeira/correios/issues/246#issuecomment-311952260>,
or mute the thread

**Comment by rafaelpatro** [comment]
Este é o [arquivo de tradução](https://github.com/pedro-teixeira/correios/blob/master/app/locale/pt_BR/PedroTeixeira_Correios.csv#L16). Qualquer modificação que fizer nele, precisará atualizar a cache de traduções.

Para que funcione no backend basta adicionar o código a seguir, [nesta linha](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L104).
```xml
    <adminhtml>
        <translate>
            <modules>
                <PedroTeixeira_Correios>
                    <files>
                        <default>PedroTeixeira_Correios.csv</default>
                    </files>
                </PedroTeixeira_Correios>
            </modules>
        </translate>
    </adminhtml>
```

Boa sorte!

**Comment by brumevi** [comment]
Rafael, conheço muito pouco de programação, você não oferece esse serviço? quero melhorar outras coisas na nossa loja também, poderia enviar algum contato de e-mail , skype, whatsapp?

**Comment by rafaelpatro** [comment]
rafaelpatro@gmail.com

**Comment by henriquemnr** [comment]
@rafaelpatro tentei inserir a nova linha dentro do CSV, mas mesmo limpando todo o cache o nome não foi alterado.... Aparece como abaixo, mesmo no CSV estando alterado. Queria deixar escrito somente carta.
Correios
10138 - CARTA COMERCIAL REGISTRADA - Em média 6 dia(s) úteis. - R$6,50
Frete

**Comment by rafaelpatro** [comment]
Dá uma conferida nos espaços. Precisa estar idêntico aos Correios. Acho q precisa 2 espaços entre COMERCIAL e REGISTRADA.

**Comment by henriquemnr** [comment]
@rafaelpatro  matou a charada! Coloquei o espaço a mais e ficou perfeito! Muito obrigado
